id: claimguardian-webhook-trigger
namespace: claimguardian
description: |
  ClaimGuardian AI - Webhook-Triggered Workflow
  
  This workflow accepts HTTP POST requests from external systems (like Vercel frontend)
  and uses Kestra's built-in AI Agent to:
  1. Summarize medical billing data from multiple systems
  2. Make decisions based on summarized data (risk assessment, appeal recommendations)
  
  Uses webhook trigger for external integration.

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    path: /claimguardian/analyze
    method: POST
    description: |
      Webhook endpoint for triggering bill analysis
      Accepts JSON payload with bill data

inputs:
  - id: bill_data
    type: JSON
    description: Medical bill data as JSON object
    defaults: |
      {
        "patient": {"name": "John Doe"},
        "procedures": [{"cpt_code": "70553", "description": "MRI brain", "billed_amount": 5000}],
        "total_billed": 5000
      }

tasks:
  # Step 1: Write bill data to temporary file for processing
  - id: write_bill_data
    type: io.kestra.plugin.fs.Write
    description: Write incoming bill data to temporary file
    content: "{{ inputs.bill_data | json }}"
    to: "/tmp/bill_{{ execution.id }}.json"

  # Step 2: AI Agent summarizes the medical bill data
  - id: ai_summarize_bill
    type: io.kestra.plugin.ai.agent.AIAgent
    description: |
      AI Agent summarizes medical billing data from multiple sources:
      - Medical bill details (procedures, costs, diagnoses)
      - CPT codes and descriptions
      - Medicare rate comparisons
      - Insurance claim information
    provider:
      type: io.kestra.plugin.ai.provider.OpenAI
      apiKey: "{{ secret('OPENAI_API_KEY') }}"
      modelName: gpt-4o-mini
    prompt: |
      You are a medical billing expert AI agent. Analyze and summarize the following medical bill data.
      
      Medical Bill Data:
      {{ read(outputs.write_bill_data.path) }}
      
      Please provide a comprehensive summary including:
      1. Patient information and claim details
      2. List of procedures with CPT codes and billed amounts
      3. Diagnoses (ICD-10 codes) if available
      4. Total billed amount
      5. Key observations about the bill (overcharges, unusual patterns, etc.)
      6. Comparison to typical Medicare rates (if known)
      
      Format your summary in clear, structured sections.
    outputFormat: JSON
    outputVariable: bill_summary

  # Step 3: Load additional data sources for context
  - id: load_cpt_reference
    type: io.kestra.plugin.core.log.Log
    description: Load CPT code reference data (simulated - in production would load from database)
    message: |
      CPT Code Reference Data Loaded:
      - 70553: MRI brain with/without contrast - Avg Cost: $3,500
      - 45378: Colonoscopy, diagnostic - Avg Cost: $3,000
      - 27447: Total knee arthroplasty - Avg Cost: $50,000
      - Medicare rates available for comparison

  # Step 4: AI Agent makes decision based on summarized data
  - id: ai_make_decision
    type: io.kestra.plugin.ai.agent.AIAgent
    description: |
      AI Agent makes decisions based on the summarized bill data:
      - Risk level assessment (HIGH, MEDIUM, LOW)
      - Appeal recommendation (APPEAL, NEGOTIATE, ACCEPT)
      - Priority level for action
    provider:
      type: io.kestra.plugin.ai.provider.OpenAI
      apiKey: "{{ secret('OPENAI_API_KEY') }}"
      modelName: gpt-4o-mini
    prompt: |
      You are a medical billing decision-making AI agent. Based on the bill summary below, make informed decisions.
      
      Bill Summary:
      {{ outputs.ai_summarize_bill.bill_summary }}
      
      CPT Reference Data:
      - 70553 (MRI brain): Typical cost $3,500, Medicare ~$400
      - 45378 (Colonoscopy): Typical cost $3,000, Medicare ~$500
      - 27447 (Knee replacement): Typical cost $50,000, Medicare ~$15,000
      
      Analyze the bill and make decisions:
      
      1. RISK_LEVEL: Assess billing risk (HIGH, MEDIUM, LOW)
         - HIGH: Overcharge >50% above typical cost or Medicare rate
         - MEDIUM: Overcharge 20-50% above typical cost
         - LOW: Within reasonable range
      
      2. RECOMMENDED_ACTION: What should the patient do? (APPEAL, NEGOTIATE, ACCEPT)
         - APPEAL: Significant overcharge detected, formal appeal recommended
         - NEGOTIATE: Some overcharge, try negotiation first
         - ACCEPT: Charges appear reasonable
      
      3. PRIORITY: How urgent is this? (URGENT, HIGH, MEDIUM, LOW)
      
      4. REASONING: Brief explanation of your decisions
      
      Return your analysis as JSON with these fields:
      {
        "risk_level": "HIGH|MEDIUM|LOW",
        "recommended_action": "APPEAL|NEGOTIATE|ACCEPT",
        "priority": "URGENT|HIGH|MEDIUM|LOW",
        "reasoning": "explanation",
        "estimated_overcharge": "$amount if applicable",
        "next_steps": ["step1", "step2", "step3"]
      }
    outputFormat: JSON
    outputVariable: decision_analysis

  # Step 5: Generate comprehensive report combining summary and decision
  - id: generate_final_report
    type: io.kestra.plugin.core.log.Log
    description: Generate final report combining AI summary and decisions
    message: |
      ========================================
      CLAIMGUARDIAN AI AGENT ANALYSIS REPORT
      ========================================
      
      Generated: {{ execution.startDate }}
      
      ---
      BILL SUMMARY (AI Generated):
      ---
      {{ outputs.ai_summarize_bill.bill_summary }}
      
      ---
      AI DECISION ANALYSIS:
      ---
      Risk Level: {{ outputs.ai_make_decision.decision_analysis.risk_level }}
      Recommended Action: {{ outputs.ai_make_decision.decision_analysis.recommended_action }}
      Priority: {{ outputs.ai_make_decision.decision_analysis.priority }}
      
      Reasoning: {{ outputs.ai_make_decision.decision_analysis.reasoning }}
      
      Estimated Overcharge: {{ outputs.ai_make_decision.decision_analysis.estimated_overcharge }}
      
      Next Steps:
      {{ outputs.ai_make_decision.decision_analysis.next_steps }}
      
      ---
      This analysis was generated using Kestra's built-in AI Agent,
      which summarized data from multiple systems and made decisions
      based on the analysis.
      ========================================

  # Step 6: Conditional task based on AI decision
  - id: route_by_decision
    type: io.kestra.plugin.core.flow.Switch
    description: Route workflow based on AI Agent decision
    value: "{{ outputs.ai_make_decision.decision_analysis.recommended_action }}"
    cases:
      APPEAL:
        - id: high_priority_appeal
          type: io.kestra.plugin.core.log.Log
          message: |
            ⚠️ HIGH PRIORITY: AI Agent recommends APPEAL
            Risk Level: {{ outputs.ai_make_decision.decision_analysis.risk_level }}
            Estimated Overcharge: {{ outputs.ai_make_decision.decision_analysis.estimated_overcharge }}
            
            Action: Generate appeal letter workflow triggered.
      NEGOTIATE:
        - id: negotiation_workflow
          type: io.kestra.plugin.core.log.Log
          message: |
            💬 NEGOTIATION RECOMMENDED: AI Agent suggests negotiation
            Risk Level: {{ outputs.ai_make_decision.decision_analysis.risk_level }}
            
            Action: Prepare negotiation strategy and contact billing department.
      ACCEPT:
        - id: accept_bill
          type: io.kestra.plugin.core.log.Log
          message: |
            ✅ BILL ACCEPTED: AI Agent determined charges are reasonable
            Risk Level: {{ outputs.ai_make_decision.decision_analysis.risk_level }}
            
            Action: No further action required, proceed with payment.

  # Step 7: Final summary
  - id: workflow_complete
    type: io.kestra.plugin.core.log.Log
    description: Workflow completion summary
    message: |
      ✅ ClaimGuardian Webhook-Triggered Workflow Complete!
      
      Summary:
      - Medical bill data received via webhook
      - AI Agent summarized data from multiple sources
      - Decision made: {{ outputs.ai_make_decision.decision_analysis.recommended_action }}
      - Risk assessment: {{ outputs.ai_make_decision.decision_analysis.risk_level }}
      
      This workflow demonstrates:
      1. ✅ Webhook trigger for external system integration
      2. ✅ Kestra's built-in AI Agent summarizing data from other systems
      3. ✅ AI Agent making decisions based on summarized data
      4. ✅ Conditional routing based on AI decisions

